### ISSUE TITLE
Doesn't play well with Sentry in a Docker container

### ISSUE THREAD

**Issue by dAnjou** [getsentry/sentry-auth-google#11]
https://hub.docker.com/_/sentry/ says (emphasis by me):

> Please note that these environment variables are provided as a jump start, and **it's highly recommended to either mount in your own config file** or utilize the sentry:onbuild variant.

`GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` are supposed to go in `sentry.conf.py`. But it's less than ideal to maintain this file ourselves. And `config.yml` doesn't seem to support these variables (yet).

So, is there a nice way to add these two variables to the settings without messing with the existing settings?

This might rather be an issue for the Sentry core project because it's an issue for [sentry-auth-github](https://github.com/getsentry/sentry-auth-github) as well.

**Comment by mattrobenolt** [comment]
What's wrong with adding these into `sentry.conf.py`? You can't even install this plugin without building your own custom image.

**Comment by dAnjou** [comment]
Right, this is what our custom image looks like:
```
FROM sentry:8.1

COPY sentry-config.yml /etc/sentry/config.yml

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["start"]
```
And this is fine because [the `config.yml` that is shipped with the base image](https://github.com/getsentry/docker-sentry/blob/136c05ff0ed9b17b06d4edb9806eea2a975398cc/8.1/config.yml) doesn't contain anything. It is *meant* to override settings options.

But [the `sentry.conf.py that is shipped with the base image](https://github.com/getsentry/docker-sentry/blob/136c05ff0ed9b17b06d4edb9806eea2a975398cc/8.1/sentry.conf.py) contains really a lot of stuff that could **and** has been(!) changed in the past. So, we really don't want to maintain a copy of it ourselves.

---
PS: Like I said, it's very likely that this issue is not solvable within this project but it came up while trying to use it.

**Comment by mattrobenolt** [comment]
This is the same expected behavior for non-Docker users fwiw. And this is our continued recommendation.

**Comment by dAnjou** [comment]
Oh, there's even a related issue: #10.

**Comment by dAnjou** [comment]
Here's how I worked around my issue:
```
FROM sentry:8.1

RUN pip install https://github.com/getsentry/sentry-auth-google/archive/master.zip

RUN mv /etc/sentry/sentry.conf.py /etc/sentry/defaults.py
COPY sentry.conf.py /etc/sentry/sentry.conf.py

COPY config.yml /etc/sentry/config.yml
```
And this our `sentry.conf.py`:
```
import sys
sys.path.append("/etc/sentry/")

from defaults import *

GOOGLE_CLIENT_ID = "XXX"
GOOGLE_CLIENT_SECRET = "YYY"
```
Hacky, I know, but it solves my issue.

**Comment by dcramer** [comment]
I'm 100% on board getting these into sentry.options, but we should encrypt them. To do that we should just cherry-pick the encryption bits out of my branch on getsentry/sentry.
