### ISSUE TITLE
Multiple domains auth

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [getsentry/sentry-auth-google#12]
Hello,

Please add the possibility to login from multiple domains. Like here https://github.com/educreations/sentry-sso-google

Thanks!

**Comment by dcramer** [comment]
This is definitely something we'd like to do.

In your case are you using multiple Google Business accounts, or simply multiple domains on the same account?

**Comment by Ilya-Kuchaev** [comment]
The first option - multiple Google Business accounts, or even regular Gmail addresses.

**Comment by dcramer** [comment]
I think we can support multiple business accounts, though we're never going to allow generic @gmail.com to authenticate as it defeats the purpose of SSO. No commitments on when this will happen, as it's a bit non trivial.

**Comment by Ilya-Kuchaev** [comment]
I see. Let's stay with at least business accounts. It's really a blocker for us. Thank you in advance!

**Comment by dcramer** [comment]
@Ilya-Kuchaev can you confirm that this is discrete business accounts or simply domain aliases?

**Comment by Ilya-Kuchaev** [comment]
Yes. We have an internal Sentry instance which handle the staging environments issues with the configured google auth. It works like a charm with our company's Google Apps domain, but we have to add some our clients from the separate Google Apps domain. They receive's invite but can't login then.

**Comment by dcramer** [comment]
@Ilya-Kuchaev I think I see the greater issue here. Right now if you have SSO enabled, and you're on-premise, we effectively force you to use SSO login. Given that we offer an option to allow access without an SSO connected account, we need to also allow you to login with standard credentials on that same screen.

**Comment by Ilya-Kuchaev** [comment]
That would be an option. If I could create the account without SSO. Just take a look at GitLab - they can authorize you with GitHub, Google, GitLab, or even with an internal username.

**Comment by dcramer** [comment]
@Ilya-Kuchaev we'll fix the auth issue, but what you're referring to on GitLab is not SSO -- its purely a shortcut for creating an account. It serves a very different purpose from Sentry's Single Sign On, which is about security and control.

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by dcramer** [comment]
Just for clarity were not actively working on this right now. It's something we'd like to improve but given that no paying customers have asked for it weve sidebarred.

**Comment by dcramer** [comment]
Closing this out since we now support multiple domains on the backend (requires updating the DB)

**Comment by t-anjan** [comment]
Is this available on sentry.io now (not self-hosted version)? If yes, how do I add a second domain?
