### ISSUE TITLE
Remove offline access to Google accounts if that's not a requirement

### ISSUE THREAD

**Issue by matthiask** [getsentry/sentry-auth-google#14]
`access_type` is set to `offline` in https://github.com/getsentry/sentry-auth-google/blob/master/sentry_auth_google/provider.py#L31, but I'm not sure why Sentry would need this? It also forces users to approve the login request again and again. Maybe that's what you want, but if not I suggest switching to `online`.

Thanks!

(Awesome product BTW, I'm a happy paying customer for almost 4 years. Not that I expect any different treatment because of this!)

**Comment by dcramer** [comment]
While we dont have to do this every time (AFAIK), it would require our system to know if it currently has the correct access. We *do* need offline access, and without that Google will appropriately give it to us as-needed. We've tried to kill it in the past and it ended up just causing harder to test issues in the system.
