### ISSUE TITLE
Authentication Error when trying to configure SSO

### ISSUE THREAD

**Issue by swapniljain14** [getsentry/sentry-auth-google#15]
While configuring SSO for on-premise sentry, I am getting this Authentication error:

```
Authentication error: The domain for your Google account is not allowed to authenticate with this provider.
```

This error comes when I click on configure for provider Google in auth section. I have followed all the mentioned steps for the integration. Do I need to add allowed domains anywhere in sentry config?

**Comment by dcramer** [comment]
It sounds like you're trying to auth with an @gmail.com account or something else not bound to your company. Our SSO is not intended to just be an easy way to login, but a definitive source of truth on if someone should have access to Sentry.

**Comment by swapniljain14** [comment]
Thanks for a quick reply @dcramer. I am not using @gmail.com account, but the company account only.

**Comment by dcramer** [comment]
@swapniljain14 the only way this error happens is if youre logging in with a gmail.com account, so I'm not sure what to tell you other than that.
