### ISSUE TITLE
invalid_client error

### ISSUE THREAD

**Issue by boskiv** [getsentry/sentry-auth-google#17]
I have create web application type of Oauth ID client. Got secret key and id, pass it into variables
but got an error when click Configure button in Sentry Project Auth section
![screen shot 2017-05-31 at 09 13 13](https://cloud.githubusercontent.com/assets/1939783/26618801/5f4b45a2-45e4-11e7-8833-bdfa26fd7db7.png)

What I done wrong ?

**Comment by dcramer** [comment]
The settings aren't configured correctly as you can see the client_id is not being passed here

**Comment by boskiv** [comment]
I have moved GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET into sentry.conf.py and it's work.
Before it was in environment variables and does not work.
I'm using docker-compose file to start.
