### ISSUE TITLE
How to whitelist multiple domains?

### ISSUE THREAD

**Issue by sanjioh** [getsentry/sentry-auth-google#18]
Hi,

I'm trying to let users login with an alias domain, as in "not the main one", configured on our company's Google account.
Looking at the code it seems to me that a whitelist option is available, but I couldn't exactly find out how to set the list in the configuration.

I'm using version 0.2.0.dev0.

Would you please give some advice? Thank you!

**Comment by dcramer** [comment]
You'll need to update the database config for the provider:

```python
provider = AuthProvider.objects.get()
provider.config['domains'] =  ['foo.com', 'bar.com']
provider.save()
```

**Comment by sanjioh** [comment]
Sorry,

but I don't manage to get this working.
I've done what you suggested, and now I am in the following situation:

$ SENTRY_CONF="/etc/sentry" sentry shell
>>> from sentry.models.authprovider import AuthProvider
>>> AuthProvider.objects.get().config
{u'domains': [u'primary.tld', u'secondary.tld'], u'domain': u'primary.tld', u'version': u'1'}

However, when I try to login with user@secondary.tld, access is still denied (top red bar with message "Authentication error: The domain for your Google account (beefree.io) is not allowed to authenticate with this provider.").

Any further hints?

Thanks a lot for your help.

**Comment by sanjioh** [comment]
Got it - the key ``domain`` must be removed from the config dict as well.
```
>>> del provider.config[u'domain']
```
Thanks again and sorry for the noise!

**Comment by dcramer** [comment]
Requires changing the database right now - nothing exposed in the UI
