### ISSUE TITLE
Cannot setup Google 

### ISSUE THREAD

**Issue by czchen** [getsentry/sentry-auth-google#26]
We have the following error message when trying to setup Google OAuth in our private sentry instance. Please help to check if there is any problem in the following configure:

The error message is
```
Authentication error: The domain for your Google account is not allowed to authenticate with this provider.
```

The sentry instance is setup via Docker. The content of `Dockerfile` is
```
FROM sentry:8.22-onbuild
```

The content of `requirements.txt` is
```
-e git+https://github.com/getsentry/sentry-auth-google.git@master#egg=sentry-auth-google
```

The content of `sentry.conf.py` is
```
GOOGLE_CLIENT_ID = '...'
GOOGLE_CLIENT_SECRET = '...
```

**Comment by silvez-dh** [comment]
Using the version referenced in this issue works for me: https://github.com/getsentry/sentry-auth-google/issues/27#issuecomment-397082005
