### ISSUE TITLE
Google login requested too often

### ISSUE THREAD

**Issue by Skyross** [getsentry/sentry-auth-google#30]
We are using Sentry on-premise and enabled Google SSO. Since that time, we start to have a bad user experience because of the login page shows too frequently (once at 5-40 minutes sometimes).

Looks like it caused by using `approval_prompt=force` parameter during auth request.
(found at https://github.com/getsentry/sentry-auth-google/blob/master/sentry_auth_google/provider.py#L31). I can contribute if anyone can confirm that is the root problem.

Or there is any other cause? Any ideas?

**Comment by dcramer** [comment]
That’s not the problem. That parameter forces the login prompt which resolved some behavioral issues. It’s unrelated to your sessions timing out. We don’t set any aggressive security constraints by default so I don’t know why this would be happening to you.

**Comment by Skyross** [comment]
@dcramer Thank you for the reply and the tip about session timing out! I will investigate this issue in this way.
