### ISSUE TITLE
Google+ api is depredated

### ISSUE THREAD

**Issue by raqqun** [getsentry/sentry-auth-google#34]
Hello i opened this ticket because i received an alert from Google about the deprecation of the Google+ API on March 7 2019.

From Google alert:
```
What do I need to know?

On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.

What do I need to do?

Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.
```

I switched from Google+ API to the Google People API but i get an error :

```
The domain for your Google account is not allowed to authenticate with this provider.
```

Do you have any plans on updating the googe sign-in integration since Google+ deprecation ?

**Comment by dcramer** [comment]
The plugin works already. Please see the readme for instructions on how to install the latest version.

**Comment by raqqun** [comment]
Please reconsider this. I saw the readme and i installed this plugin more than a year ago and everything went well. But since the Google+ API deprecation i deactivated it to use People API instead to get user info and i can't sign-in anymore. I use sentry 9.0.0 with docker on-premise.

**Comment by dcramer** [comment]
What I’m saying is that the current version of the plugin already works without g+ and has for some time.
