### ISSUE TITLE
New release on pypi (0.2.0-dev0)?

### ISSUE THREAD

**Issue by sbadia** [getsentry/sentry-auth-google#8]
Hi!

Just to wonder if it's possible to push a new release of `sentry-auth-google` on pypi? Because the actual version `0.1.0` doesn't work with sentry > `8.x.x`.

Thanks in advance!

**Comment by NotSqrt** [comment]
Are you sure about that ? I have no problem with any of the 8.x.x releases ..

**Comment by sbadia** [comment]
I've maybe a particular setup, but I use sentry `8.5.1` (the `latest` release), my GoogleApps domain is `domain.com` and all my sentry are deployed under `domain.net` tld, changes about this use case are commited between `0.1.0` and actual `master` branch https://github.com/getsentry/sentry-auth-google/compare/0.1.0...master.

With sentry `8.5.1` + sentry-auth-google `0.1.0` in cant configure the OAuth provider.

**Comment by NotSqrt** [comment]
Makes sense..

I use the same domain for google apps and sentry ..

**Comment by dcramer** [comment]
We're looking into this as the domain change has been causing us issues on getsentry.com as well.

It's not as simple as reverting at this point, as we need to support both models and transition accounts cleanly.

**Comment by dcramer** [comment]
We're going to simply move to using the id_token which brings back the 'hd' param, and will allow us to re-bind restrictions to the apps domain.

**Comment by dcramer** [comment]
Also we recommend installing from Git rather than PyPi, so I'm closing this out.

**Comment by sbadia** [comment]
ack, thanks for the reply!
